FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache openssl

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --frozen-lockfile

COPY docker-entrypoint.dev.sh /usr/local/bin/
RUN sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.dev.sh \
  && chmod +x /usr/local/bin/docker-entrypoint.dev.sh

EXPOSE 3000

CMD ["sh", "/usr/local/bin/docker-entrypoint.dev.sh"]
